### ISSUE TITLE
error ; database can not work 

### ISSUE THREAD

**Issue by connect2robiul** [bradtraversy/mean_mytasklist#5]
`events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Function.listen (/Users/robiulislam/Downloads/mean_mytasklist-master-0/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/robiulislam/Downloads/mean_mytasklist-master-0/server.js:27:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by Pankajtanwarbanna** [comment]
Looks like port 3000 is busy. In server.js made below changes -

`var port = process.env.PORT || 3000;`

Now, PORT is environmental variable and you can pass any port you want (except 6000 :)
